-- Automated QB sync, integrity checking, task management, AI metrics
-- Phase 1 of QB data retrieval & AI-enhancement architecture
-- ============================================================

-- ============================================================
-- Sync Runs — Track every QB sync execution
-- ============================================================
CREATE TABLE IF NOT EXISTS sync_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  sync_type TEXT NOT NULL
    CHECK (sync_type IN ('scheduled_weekly', 'scheduled_daily', 'manual')),
  started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at TIMESTAMPTZ,
  status TEXT NOT NULL DEFAULT 'running'
    CHECK (status IN ('running', 'success', 'error')),
  since_date DATE,
  entities_fetched JSONB,            -- {purchases: 42, deposits: 10, transfers: 5, journal_entries: 2}
  entities_new INTEGER DEFAULT 0,
  entities_updated INTEGER DEFAULT 0,
  error_message TEXT,
  triggered_by TEXT,                  -- 'cron', 'admin:rahul@email.com'
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_sync_runs_status ON sync_runs(status);
CREATE INDEX IF NOT EXISTS idx_sync_runs_completed ON sync_runs(completed_at DESC);

ALTER TABLE sync_runs ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'sync_runs' AND policyname = 'Authenticated read sync_runs') THEN
    CREATE POLICY "Authenticated read sync_runs" ON sync_runs FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'sync_runs' AND policyname = 'Service write sync_runs') THEN
    CREATE POLICY "Service write sync_runs" ON sync_runs FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ============================================================
-- Integrity Findings — Dynamic data quality issues
-- ============================================================
CREATE TABLE IF NOT EXISTS integrity_findings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  finding_type TEXT NOT NULL,          -- 'missing_category', 'missing_receipt', 'duplicate', 'stale_account', etc.
  severity TEXT NOT NULL DEFAULT 'warning'
    CHECK (severity IN ('critical', 'warning', 'info')),
  entity_type TEXT,                    -- 'qb_transaction', 'account', 'vendor', 'receipt'
  entity_id UUID,
  title TEXT NOT NULL,
  description TEXT,
  suggested_action TEXT,
  auto_fixable BOOLEAN DEFAULT false,
  resolved_at TIMESTAMPTZ,
  resolved_by TEXT,
  resolution_notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_integrity_findings_type ON integrity_findings(finding_type);
CREATE INDEX IF NOT EXISTS idx_integrity_findings_severity ON integrity_findings(severity);
CREATE INDEX IF NOT EXISTS idx_integrity_findings_unresolved ON integrity_findings(resolved_at) WHERE resolved_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_integrity_findings_entity ON integrity_findings(entity_type, entity_id);

ALTER TABLE integrity_findings ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'integrity_findings' AND policyname = 'Authenticated read integrity_findings') THEN
    CREATE POLICY "Authenticated read integrity_findings" ON integrity_findings FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'integrity_findings' AND policyname = 'Service write integrity_findings') THEN
    CREATE POLICY "Service write integrity_findings" ON integrity_findings FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'integrity_findings' AND policyname = 'Authenticated update integrity_findings') THEN
    CREATE POLICY "Authenticated update integrity_findings" ON integrity_findings FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ============================================================
-- Todos — Human task queue generated by AI + integrity checks
-- ============================================================
CREATE TABLE IF NOT EXISTS todos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  title TEXT NOT NULL,
  description TEXT,
  source TEXT NOT NULL DEFAULT 'manual'
    CHECK (source IN ('integrity_check', 'ai_categorization', 'receipt_mismatch', 'sync_error', 'manual')),
  source_entity_type TEXT,             -- 'integrity_finding', 'qb_transaction', 'receipt', 'sync_run'
  source_entity_id UUID,
  priority TEXT NOT NULL DEFAULT 'medium'
    CHECK (priority IN ('urgent', 'high', 'medium', 'low')),
  status TEXT NOT NULL DEFAULT 'open'
    CHECK (status IN ('open', 'in_progress', 'done', 'auto_resolved', 'dismissed')),
  assigned_to TEXT DEFAULT 'owner'
    CHECK (assigned_to IN ('owner', 'bookkeeper', 'ai')),
  due_date DATE,
  resolved_at TIMESTAMPTZ,
  resolved_by TEXT,
  resolution_notes TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_todos_status ON todos(status);
CREATE INDEX IF NOT EXISTS idx_todos_priority ON todos(priority);
CREATE INDEX IF NOT EXISTS idx_todos_assigned ON todos(assigned_to);
CREATE INDEX IF NOT EXISTS idx_todos_open ON todos(status, priority) WHERE status IN ('open', 'in_progress');
CREATE INDEX IF NOT EXISTS idx_todos_source ON todos(source_entity_type, source_entity_id);

ALTER TABLE todos ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'todos' AND policyname = 'Authenticated read todos') THEN
    CREATE POLICY "Authenticated read todos" ON todos FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'todos' AND policyname = 'Service write todos') THEN
    CREATE POLICY "Service write todos" ON todos FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'todos' AND policyname = 'Authenticated manage todos') THEN
    CREATE POLICY "Authenticated manage todos" ON todos FOR ALL TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ============================================================
-- QB Writeback Queue — Proposed changes to push back to QB
-- ============================================================
CREATE TABLE IF NOT EXISTS qb_writeback_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  qb_entity_type TEXT NOT NULL,        -- 'Purchase', 'Deposit', 'JournalEntry', etc.
  qb_entity_id TEXT NOT NULL,
  field_name TEXT NOT NULL,            -- 'PrivateNote', 'AccountRef', 'Line', etc.
  old_value TEXT,
  new_value TEXT NOT NULL,
  reason TEXT,
  status TEXT NOT NULL DEFAULT 'proposed'
    CHECK (status IN ('proposed', 'approved', 'executed', 'failed', 'rejected')),
  approved_by TEXT,
  approved_at TIMESTAMPTZ,
  executed_at TIMESTAMPTZ,
  error_message TEXT,
  created_at TIMESTAMPTZ DEFAULT now(),
  updated_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_writeback_status ON qb_writeback_queue(status);
CREATE INDEX IF NOT EXISTS idx_writeback_entity ON qb_writeback_queue(qb_entity_type, qb_entity_id);

ALTER TABLE qb_writeback_queue ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'qb_writeback_queue' AND policyname = 'Authenticated read writeback') THEN
    CREATE POLICY "Authenticated read writeback" ON qb_writeback_queue FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'qb_writeback_queue' AND policyname = 'Service write writeback') THEN
    CREATE POLICY "Service write writeback" ON qb_writeback_queue FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'qb_writeback_queue' AND policyname = 'Authenticated update writeback') THEN
    CREATE POLICY "Authenticated update writeback" ON qb_writeback_queue FOR UPDATE TO authenticated USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ============================================================
-- AI Metrics — Track AI categorization accuracy over time
-- ============================================================
CREATE TABLE IF NOT EXISTS ai_metrics (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  period_start DATE NOT NULL,
  period_end DATE NOT NULL,
  total_ai_categorized INTEGER DEFAULT 0,
  human_approved INTEGER DEFAULT 0,
  human_overridden INTEGER DEFAULT 0,
  accuracy_pct NUMERIC(5,2),
  avg_confidence NUMERIC(3,2),
  new_rules_created INTEGER DEFAULT 0,
  rules_deactivated INTEGER DEFAULT 0,
  created_at TIMESTAMPTZ DEFAULT now(),
  UNIQUE(period_start, period_end)
);

ALTER TABLE ai_metrics ENABLE ROW LEVEL SECURITY;
DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ai_metrics' AND policyname = 'Authenticated read ai_metrics') THEN
    CREATE POLICY "Authenticated read ai_metrics" ON ai_metrics FOR SELECT TO authenticated USING (true);
  END IF;
  IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE tablename = 'ai_metrics' AND policyname = 'Service write ai_metrics') THEN
    CREATE POLICY "Service write ai_metrics" ON ai_metrics FOR ALL TO service_role USING (true) WITH CHECK (true);
  END IF;
END $$;

-- ============================================================
-- Extend qb_transactions for soft-delete and cross-source matching
-- ============================================================
ALTER TABLE qb_transactions
  ADD COLUMN IF NOT EXISTS is_deleted BOOLEAN DEFAULT false,
  ADD COLUMN IF NOT EXISTS deleted_detected_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS matched_statement_txn_id UUID,
  ADD COLUMN IF NOT EXISTS matched_statement_type TEXT;  -- 'cc_transaction', 'checking_transaction'

CREATE INDEX IF NOT EXISTS idx_qb_txn_not_deleted ON qb_transactions(is_deleted) WHERE is_deleted = false;

-- ============================================================
-- Register new tabs in page_display_config
-- ============================================================
INSERT INTO page_display_config (section, tab_key, tab_label, is_visible, sort_order)
VALUES
  ('bookkeeping', 'dashboard', 'Dashboard', true, 0),
  ('bookkeeping', 'tasks', 'Tasks', true, 55),
  ('bookkeeping', 'tax-report', 'Tax Report', true, 90)
ON CONFLICT (section, tab_key) DO NOTHING;
