"use client";

import { useEffect, useState, useCallback } from "react";
import { supabase } from "@/lib/supabase";
import { TabHeader, TabErrorBanner, TabEmptyState } from "@/components/tabs";

interface Todo {
  id: string;
  title: string;
  description: string | null;
  source: string;
  source_entity_type: string | null;
  source_entity_id: string | null;
  priority: string;
  status: string;
  assigned_to: string;
  due_date: string | null;
  resolved_at: string | null;
  resolved_by: string | null;
  resolution_notes: string | null;
  created_at: string;
  updated_at: string;
}

type FilterStatus = "open" | "in_progress" | "done" | "all";

const PRIORITY_STYLES: Record<string, { bg: string; text: string; label: string }> = {
  urgent: { bg: "bg-red-50", text: "text-red-700", label: "Urgent" },
  high: { bg: "bg-orange-50", text: "text-orange-700", label: "High" },
  medium: { bg: "bg-blue-50", text: "text-blue-700", label: "Medium" },
  low: { bg: "bg-slate-50", text: "text-slate-600", label: "Low" },
};

const SOURCE_LABELS: Record<string, string> = {
  integrity_check: "Integrity Check",
  ai_categorization: "AI Categorization",
  receipt_mismatch: "Receipt Mismatch",
  sync_error: "Sync Error",
  manual: "Manual",
};

const STATUS_LABELS: Record<string, { label: string; icon: string }> = {
  open: { label: "Open", icon: "⬚" },
  in_progress: { label: "In Progress", icon: "▶" },
  done: { label: "Done", icon: "✓" },
  auto_resolved: { label: "Auto-Resolved", icon: "🤖" },
  dismissed: { label: "Dismissed", icon: "✕" },
};

export default function TasksTab() {
  const [todos, setTodos] = useState<Todo[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [filter, setFilter] = useState<FilterStatus>("open");
  const [counts, setCounts] = useState<Record<string, number>>({});

  const fetchTodos = useCallback(async () => {
    setLoading(true);
    let query = supabase
      .from("todos")
      .select("*")
      .order("priority", { ascending: true })
      .order("created_at", { ascending: false });

    if (filter === "open") {
      query = query.in("status", ["open", "in_progress"]);
    } else if (filter !== "all") {
      query = query.eq("status", filter);
    }

    const { data, error: fetchError } = await query.limit(100);

    if (fetchError) {
      setError(fetchError.message);
    } else {
      setTodos(data || []);
    }
    setLoading(false);
  }, [filter]);

  const fetchCounts = useCallback(async () => {
    const [open, inProgress, done] = await Promise.all([
      supabase.from("todos").select("id", { count: "exact", head: true }).eq("status", "open"),
      supabase.from("todos").select("id", { count: "exact", head: true }).eq("status", "in_progress"),
      supabase.from("todos").select("id", { count: "exact", head: true }).eq("status", "done"),
    ]);
    setCounts({
      open: (open.count || 0) + (inProgress.count || 0),
      done: done.count || 0,
    });
  }, []);

  useEffect(() => {
    fetchTodos();
    fetchCounts();
  }, [fetchTodos, fetchCounts]);

  const updateStatus = async (id: string, newStatus: string) => {
    const updates: Record<string, any> = {
      status: newStatus,
      updated_at: new Date().toISOString(),
    };
    if (newStatus === "done" || newStatus === "dismissed") {
      updates.resolved_at = new Date().toISOString();
      updates.resolved_by = "owner";
    }

    const { error: updateError } = await supabase
      .from("todos")
      .update(updates)
      .eq("id", id);

    if (updateError) {
      setError(updateError.message);
    } else {
      await Promise.all([fetchTodos(), fetchCounts()]);
    }
  };

  const formatDate = (d: string) => {
    return new Date(d).toLocaleDateString("en-US", {
      month: "short",
      day: "numeric",
    });
  };

  const filterTabs: { key: FilterStatus; label: string }[] = [
    { key: "open", label: `Open (${counts.open || 0})` },
    { key: "done", label: `Done (${counts.done || 0})` },
    { key: "all", label: "All" },
  ];

  return (
    <div>
      <TabHeader
        title="Tasks"
        description="Action items generated by AI integrity checks and sync issues"
      />

      <TabErrorBanner error={error} onDismiss={() => setError(null)} />

      {/* Filter tabs */}
      <div className="flex gap-1 mb-4 bg-slate-100 rounded-lg p-1 w-fit">
        {filterTabs.map((tab) => (
          <button
            key={tab.key}
            onClick={() => setFilter(tab.key)}
            className={`px-3 py-1.5 text-sm font-medium rounded-md transition-colors ${
              filter === tab.key
                ? "bg-white text-slate-900 shadow-sm"
                : "text-slate-600 hover:text-slate-900"
            }`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {loading ? (
        <TabEmptyState message="Loading tasks..." />
      ) : todos.length === 0 ? (
        <TabEmptyState title="No tasks">
          Tasks will appear here when integrity checks or AI processing detect issues that need attention.
        </TabEmptyState>
      ) : (
        <div className="space-y-2">
          {todos.map((todo) => {
            const priority = PRIORITY_STYLES[todo.priority] || PRIORITY_STYLES.medium;
            const statusInfo = STATUS_LABELS[todo.status] || STATUS_LABELS.open;

            return (
              <div
                key={todo.id}
                className={`rounded-xl border border-slate-200 bg-white p-4 ${
                  todo.status === "done" || todo.status === "auto_resolved" || todo.status === "dismissed"
                    ? "opacity-60"
                    : ""
                }`}
              >
                <div className="flex items-start gap-3">
                  <div className="flex-1 min-w-0">
                    <div className="flex items-center gap-2 mb-1">
                      <span className={`inline-flex items-center px-2 py-0.5 rounded text-xs font-medium ${priority.bg} ${priority.text}`}>
                        {priority.label}
                      </span>
                      <span className="text-xs text-slate-400">
                        {SOURCE_LABELS[todo.source] || todo.source}
                      </span>
                      {todo.due_date && (
                        <span className="text-xs text-slate-400">
                          Due {formatDate(todo.due_date)}
                        </span>
                      )}
                    </div>
                    <h3 className="text-sm font-medium text-slate-900">{todo.title}</h3>
                    {todo.description && (
                      <p className="text-sm text-slate-500 mt-0.5">{todo.description}</p>
                    )}
                    {todo.resolution_notes && (
                      <p className="text-xs text-slate-400 mt-1 italic">
                        {statusInfo.icon} {todo.resolution_notes}
                      </p>
                    )}
                  </div>
                  <div className="flex items-center gap-1 flex-shrink-0">
                    {todo.status === "open" && (
                      <>
                        <button
                          onClick={() => updateStatus(todo.id, "in_progress")}
                          className="px-2 py-1 text-xs rounded bg-blue-50 text-blue-700 hover:bg-blue-100 transition-colors"
                        >
                          Start
                        </button>
                        <button
                          onClick={() => updateStatus(todo.id, "done")}
                          className="px-2 py-1 text-xs rounded bg-green-50 text-green-700 hover:bg-green-100 transition-colors"
                        >
                          Done
                        </button>
                        <button
                          onClick={() => updateStatus(todo.id, "dismissed")}
                          className="px-2 py-1 text-xs rounded bg-slate-50 text-slate-500 hover:bg-slate-100 transition-colors"
                        >
                          Dismiss
                        </button>
                      </>
                    )}
                    {todo.status === "in_progress" && (
                      <button
                        onClick={() => updateStatus(todo.id, "done")}
                        className="px-2 py-1 text-xs rounded bg-green-50 text-green-700 hover:bg-green-100 transition-colors"
                      >
                        Complete
                      </button>
                    )}
                  </div>
                </div>
                <div className="mt-2 text-xs text-slate-400">
                  Created {formatDate(todo.created_at)} · Assigned to {todo.assigned_to}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
